server:
  port: ${SERVER_PORT:8082}
  
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:hogar360_user_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:toor}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
jwt:
  secret: ${JWT_SECRET}
  user: ${JWT_USER:AUTH0JWT_BACKEND}
  expiration: ${JWT_EXPIRATION:86400000}

# Uncomment the following lines to enable debug logging
  
#logging:
#  level:
#    root: debug